# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_user_id', models.CharField(max_length=40, unique=True)),
                ('key_salt', models.CharField(max_length=200)),
                ('public_key', models.CharField(max_length=2000)),
                ('private_key', models.CharField(max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('create_user', 'create a user'), ('read_user', 'read a user'), ('update_user', 'update a user'), ('delete_user', 'delete a user')),
            },
        ),
    ]
