# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='last_signed_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
