# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_userdata_last_signed_in_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='last_signed_in_date',
        ),
    ]
