# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_remove_userdata_last_signed_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='disable_search',
            field=models.BooleanField(default=0),
        ),
    ]
