# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(max_length=40, unique=True)),
                ('deleted', models.BooleanField(default=0)),
                ('read', models.BooleanField(default=0)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(default='no subject', max_length=1000)),
                ('message_text', models.TextField(default='no msg')),
                ('integrity_signature', models.TextField(default='INVALID SIGNATURE')),
                ('plaintext_subject', models.CharField(default='no subject', max_length=1000)),
                ('plaintext_message_text', models.TextField(default='no msg')),
                ('recieve_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_messages', to=settings.AUTH_USER_MODEL)),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['send_date'],
                'permissions': (('create_message', 'create a message'), ('read_message', 'read a message'), ('update_message', 'update a message'), ('delete_message', 'delete a message')),
            },
        ),
    ]
