# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='disable_search',
            field=models.BooleanField(default=0),
        ),
    ]
