# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_privatemessage_disable_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='disable_search',
        ),
    ]
